name: Reusable-deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: Please enter the name of deployable artifact files
        required: false
        default: dist
        type: string
    outputs:
      result: 
        description: The result of deployment section
        value: ${{ jobs.deploy.outputs.outcome }}

jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output Information
        run: echo "Deploying and Updating.."
      - name: Set Output Result
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT